version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elvin
      POSTGRES_PASSWORD: elvin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: elvin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  db:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: